name: Survival
version: 1.0
main: me.lehtinenkaali.Survival
api-version: 1.16
author: Lehtinenkaali
description: Survival plugin to Hohto
depend:
  - Vault
  - PlaceholderAPI
commands:
  tilastot:
  pankki:
  uhkapelaa:



